package com.notarist.search.application.routing;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Fail-closed guard around the "an LLM may never answer a fact" rule.
 *
 * <p>The router already enforces this <em>positively</em>: a factual question is matched to a SQL
 * strategy, and SQL strategies hold no reference to {@code RagPort}, so there is no code path from a
 * count to a language model. This class is the <em>negative</em> assertion — the thing that turns a
 * design intention into a test that fails.
 *
 * <p>Why both? Because the positive rule is only as good as the classifier and the wiring. If a
 * future change accidentally makes an LLM strategy claim {@code supports()} for a STATISTICS query,
 * the positive rule silently breaks and nobody notices — the answers just quietly become
 * hallucinated. The guard turns that silent failure into a loud one.
 *
 * <p>It runs twice per request:
 * <ol>
 *   <li><b>Before execution</b> — refuses to run an LLM strategy for an LLM-forbidden category.</li>
 *   <li><b>After execution</b> — refuses to return a result whose metadata says an LLM was invoked
 *       for an LLM-forbidden category.</li>
 * </ol>
 * The second check is the one that catches a strategy lying about {@link AnswerStrategy#usesLlm()}.
 */
@Component
public class FactualQueryGuard {

    private static final Logger log = LoggerFactory.getLogger(FactualQueryGuard.class);

    /**
     * Pre-execution: the selected strategy must be permitted to answer this category.
     *
     * @throws LlmForbiddenException if an LLM-backed strategy was selected for a factual/status query
     */
    public void assertStrategyAllowed(ClassifiedQuery query, AnswerStrategy strategy) {
        if (!query.isLlmEligible() && strategy.usesLlm()) {
            log.error("GUARD VIOLATION (pre): LLM strategy '{}' selected for LLM-forbidden category {} — query='{}'",
                    strategy.name(), query.category(), query.rawQuery());
            throw new LlmForbiddenException(
                    "Strategy '" + strategy.name() + "' invokes an LLM but the query category "
                            + query.category() + " forbids it. A " + query.category()
                            + " question must be answered from the database.");
        }
    }

    /**
     * Post-execution: the result must not claim an LLM was invoked for a forbidden category.
     *
     * <p>Fails the request rather than returning the answer. An answer that reached a user having
     * been generated by a model when it should have come from SQL is worse than an error — the user
     * cannot tell the difference, and will act on it.
     */
    public void assertResultAllowed(ClassifiedQuery query, AnswerResult result) {
        if (!query.isLlmEligible() && result.metadata().llmInvoked()) {
            log.error("GUARD VIOLATION (post): strategy '{}' invoked an LLM for LLM-forbidden category {} — query='{}'",
                    result.metadata().strategyUsed(), query.category(), query.rawQuery());
            throw new LlmForbiddenException(
                    "Strategy '" + result.metadata().strategyUsed() + "' invoked an LLM for category "
                            + query.category() + ", which forbids LLM-generated answers.");
        }
    }

    /**
     * Whether an unanswerable factual question may be retried against the LLM. Always false.
     *
     * <p>Exists as a named, documented method rather than an implicit absence, because "the SQL
     * returned nothing, let's just ask the model" is the single most tempting change anyone will
     * ever propose to this file — and it would silently reintroduce exactly the class of fabricated
     * legal answer this whole sprint removes. An empty count is the answer zero. A missing table is
     * "not available yet". Neither is an invitation to guess.
     */
    public boolean mayFallBackToLlm(ClassifiedQuery query) {
        return false;
    }

    /** Thrown when the LLM boundary is violated. Fails the request; never degrades to an LLM answer. */
    public static class LlmForbiddenException extends RuntimeException {
        public LlmForbiddenException(String message) {
            super(message);
        }
    }
}
